### ISSUE TITLE
TMDB not working anymore ?

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#35]
Just returned to this fantastic script. Ive checked and double checked my settings, tmdb api etc and its not pulling any trailers from the TMDB for me. And no error reports etc. Its just skipping them as if trailers don't exist on there, and yes verified the trailers are there on each of the titles.

Apple trailers are fine.

**Comment by airship-david** [comment]
Hey @danz0l , truthfully I've only been using the script on the rewrite branch for a while now so I haven’t been monitoring this version as much as I should and I sort of need to revisit the project. However, I just tested it out and it worked for my test case. I’m assuming you have tautulli or radarr firing the script but have you tried running it manually like below? Any extra info you could provide might help me troubleshoot some more.

```
python3 download.py --title "Braveheart" --year "1995" --directory "/path/to/directory"
```

**Comment by danz0l** [comment]
Hey David. No ive been using it via batch and pointing it to a directory.
Say the film "300" just doesnt find a trailer :(

**Comment by airship-david** [comment]
Ok so what happens when you run the command below? When you run the download_all.py script, it just calls a command like this over and over as it iterates through all of the folder names. This just downloaded a trailer from TMDB for me.

```
python3 download.py --title "300" --year "2007" --directory "/Users/davidengel/Downloads"
```

I also just tested the download_all.py script against the folder structure below and it downloaded the trailers without any issues for me.

-Movies
—300 (2007)
—Braveheart (1995)

Are you positive that your API key is able to connect to TMDB? What happens when you put the following in your web browser with your api key plugged in?

```
https://api.themoviedb.org/3/movie/popular?api_key=<your api key>
```

**Comment by danz0l** [comment]
hi David. Well doing this manually works. So i guess the download_all is
the issue ?

**Comment by danz0l** [comment]
David please please please accept my apologies. After further investigation
it appears that although i heavily rely on Radarr for my movie name
convention, it appears that Radarr thinks the year for 300 is 2006, and NOT
2007. Its a very weird one for instance as it links to the TMDB page that
clearly states its 2007. Thus the script will never find it. I am on the
now assumption that the others it can't find is down to that arcane naming
convention.

Script still functioning as it should :)

**Comment by airship-david** [comment]
Ah yeah that makes sense. That’s an issue I’ve come across as well. No worries! There are still some bugs to work out with this project so please feel free to report anything you come across.
