### ISSUE TITLE
ERROR: Failed to connect to TMDB. Check your api key.

### ISSUE THREAD

**Issue by EasyNT** [airship-david/Trailer-Downloader#38]
I always get this error, API key is correct. What can I change in the code to see the actual problem?

**Comment by airship-david** [comment]
Hmmm what happens when you connect to the api in your browser using the example below? 

```
https://api.themoviedb.org/3/movie/popular?api_key=<your api key>
```

Do you have other things connecting to TMDB using that same API key? I know I need to alter the code a bit so that it catches when you go over TMDB’s API request limit and forces you to pause until you’re good again but that will ONLY be an issue if you are using the API key with multiple scripts/applications at once on the same IP address.

As for what should be modified, give me a bit and I’ll come up with something. You can see documentation for what we’re using to connect to TMDB at the link below.

```
https://github.com/celiao/tmdbsimple
```

**Comment by EasyNT** [comment]
Hi, thanks for your quick answer. The link with my api key in the browser works fine. Also I don't have any other apps on that api key. But I was thinking it could be any kind of TMDB limitation, I call your downloader each time Radarr finished downloading a movie and there it works most of the time, but when want to scan all my movies and catch all missing trailers, it's there when I hit this error 99% of all requests...

Would it be possible to just change a line or two of your code to see the actual error from TMDB?

**Comment by airship-david** [comment]
Sorry for the long delay! Were you able to get to the bottom of this issue? If not, I've added some better error handling to the TMDB api calls in v1.09 that should point you in the right direction. Cheers!
