### ISSUE TITLE
Youtube.dl no longer working on updates

### ISSUE THREAD

**Issue by danz0l** [airship-david/Trailer-Downloader#39]
It appears that youtube.dl has been updated quite a lot since the code was written and now all youtube links to downloads dont resolve and fail. There is nowhere i can see to get the youtube version downloaded pertained in the requirements.txt

**Comment by airship-david** [comment]
Thanks @danz0l. I will update the requirements.txt file today.

You can run the command below to update the youtube-dl package directly:

```
pip install --upgrade youtube-dl
```

This is also useful if you want to see any outdated packages you’ve installed with pip:

```
pip list --outdated
```

**Comment by airship-david** [comment]
The packages have been upgraded to the latest versions in v1.09. Please note that in order to fix the youtube-dl bug I also had to drop support for python 2.7 (end of life). Make sure you’re using python 3.0+ and update to the latest version of the scripts and you should be up and running again. Cheers!
