### ISSUE TITLE
Request Output: "Trailer already present"

### ISSUE THREAD

**Issue by sasagr** [airship-david/Trailer-Downloader#50]
I like the output SUCCESS: Trailer Downloaded
Can you also add something like:
Download skipped, Trailer already present.

Thanks 

Update. I see you have in download.py the following lines

if downloaded:
                print('\033[92mSUCCESS:\033[0m Trailer downloaded.')

            else:
                print('\033[91mERROR:\033[0m No trailer found.')

        else:
            print('\033[93mWARNING:\033[0m Already downloaded.')

but only "Trailer downloaded" works with me. Can you pls double check it again?

**Comment by sasagr** [comment]
Update2

I made some test and I realized that the issue is present only with download_all
See my test
sasagr@xxxx:~/Trailer-Downloader$ python3 download_all.py -d "/yyy/media/Movies/"
Airplane! (1980)
SUCCESS: Trailer downloaded.
sasagr@xxxx:~/Trailer-Downloader$ python3 download_all.py -d "/yyy/media/Movies/"
sasagr@xxxx:~/Trailer-Downloader$

if I use instead..
sasagr@xxxx:~/Trailer-Downloader$ python3 download.py --title "Airplane!" --year "1980" --directory "/yyy/media/Movies/Airplane! (1980)"
SUCCESS: Trailer downloaded.
sasagr@xxxx:~/Trailer-Downloader$ python3 download.py --title "Airplane!" --year "1980" --directory "/yyy/media/Movies/Airplane! (1980)"
WARNING: Already downloaded.

**Comment by sasagr** [comment]
maybe I fixed it?


[download_all.zip](https://github.com/airship-david/Trailer-Downloader/files/4420180/download_all.zip)

**Comment by airship-david** [comment]
I’m not sure I want to add this so I’ll have to think about it. I intentionally did not include this in the download_all.py script because when you have a lot of movies the output will get clogged up with all of the trailers that already exist and it will be difficult to just see a list of what’s missing. I guess this can be useful for just seeing that the script is working but in practice I don’t think it would add much to the project.
