### ISSUE TITLE
Tautulli Download Script: Year and Title as Parameter

### ISSUE THREAD

**Issue by MrGiga** [airship-david/Trailer-Downloader#53]
Any reason that the ability to pass those items as a parameter is not implemented in the download script (download_tautulli.py)?

**Comment by airship-david** [comment]
Did you read my comment on your other issue? This was removed due to duplicates getting downloaded with slightly different names when the download_all.py script is used. The easiest way to solve this was to have the tautulli script extract the title and year from the movie folder name instead since this is how the download_all.py and download_radarr.py script do it. Only the regular download.py script will ask you for a title and year. All of the extra scripts that help with automation will not. If your movie folders are not in the correct format, I'd recommend reverting back to v1.09. You should really consider formatting your movie folders properly for Plex though (link below). If you like this project, please consider giving it a star for some support.

https://support.plex.tv/articles/naming-and-organizing-your-movie-media-files/

https://github.com/airship-david/Trailer-Downloader/releases/tag/v1.09

**Comment by airship-david** [comment]
Closing this for now but we can reopen it if necessary.
